# Метод получения центра векторов по умолчанию при создании области схематики (если не указано).
# FROM_PLAYER - создаёт схематику, центр которой является локация игрока на момент создания (метод WorldEdit)
# VECTOR_CENTER - создаёт схематику, находя центр исходя из двух точек самой схематики
default_save_mode: FROM_PLAYER
# Метод установки точки через команду по умолчанию
# CURRENT_LOCATION - установит точку в локации игрока после отправки команды (Метод WorldEdit)
# SEEING_LOCATION - установит точку в локации, куда игрок смотрит (если блоков нет - будет использован первый метод)
default_select_pos_mode: CURRENT_LOCATION
# Предмет, нужный для выделения точек (ЛКМ - первая точка, ПКМ - вторая точка)
pos_item:
  material: IRON_AXE
  displayName: "Топор выделения"
  lore:
    - " "
    - "&f ЛКМ - Первая точка"
    - "&f ПКМ - Вторая точка"
    - " "
messages:
  reload: "Вы успешно перезагрузили плагин!" # перезагрузка плагина
  get: "Вы успешно получили предмет для установки точек!" # сообщение при выдаче предмета себе
  selectPos: "Вы успешно выделили точку №[pos]" # выделение точки №[pos]
  save: "Вы успешно сохранили схематику [id]" # сохранение в файл новой схематики
  unload: "Вы успешно выгрузили схематику [id] из плагина!"
  loadToClipboard: "Вы успешно загрузили схематику [id] в буфер обмена" # загрузка схематики [id] в буфер обмена игрока
  clipboardIsEmpty: "Ваш буфер обмена пуст!" # попытка загрузки схематики из пустого буфера обмена
  paste: "Вы успешно вставили в мир схематику [id]" # вставка схематики в мир
  undo: "Вы успешно вернулись на одно действие назад!"
  noSchemsForUndo: "У вас нет ни одной загруженной схематики!"
  schemNotExists: "Данной схематики не существует!" # попытка вставки несуществующей схематики
  schemNowExists: "Схематика [id] уже существует!" # попытка сохранения схемы, которая уже есть в памяти
  noSelectedPoses: "Для начала выделите точки!" # сообщение если не выбраны точки для создания схематики
  noArgs: "У вас не хватает аргументов!"